apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: caip-audience-intelligence
  namespace: nielsen-ai
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - caip-api.nielsen.com
    secretName: caip-tls-secret
  rules:
  - host: caip-api.nielsen.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: caip-audience-intelligence
            port:
              number: 80
      - path: /docs
        pathType: Prefix
        backend:
          service:
            name: caip-audience-intelligence
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: caip-audience-intelligence-hpa
  namespace: nielsen-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: caip-audience-intelligence
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Pods
        value: 1
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60